#Eureka-Client Config
eureka:
  client:
    enabled: true
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# disable security when connecting to server
management:
  security:
    enabled:false

#Giving microsevice endpoints
microservice:
  EMS-DASHBOARD:
    endpoints:
      endpoint:
        uri[0]:http://EMS-SEARCH/apisearch/employee/find/
        uri[1]:http://EMS-SEARCH/apisearch/addEmployee
        uri[2]:http://EMS-SEARCH/apisearch/employee/findAll
        uri[3]:http://EMS-SEARCH/apisearch/employee/delete/
        uri[4]:http://EMS-SEARCH/apisearch/updateEmployee 
