#Eureka-Client Config
eureka:
  client:
    enabled: true
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# disable security when connecting to server
management:
  security:
    enabled:false

#Giving microsevice endpoints
microservice:
  ems-dashboard:
    endpoints:
      endpoint:
        get:
          uri:http://EMS-SEARCH/apisearch/employee/find/
        add:
          uri:http://EMS-SEARCH/apisearch/addEmployee
        getall:
          uri:http://EMS-SEARCH/apisearch/employee/findAll
        delete:
          uri:http://EMS-SEARCH/apisearch/employee/delete/
        update:
          uri:http://EMS-SEARCH/apisearch/updateEmployee 
